# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class AdaguBodanItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass

class Bodan(scrapy.Item):
    league=scrapy.Field()
    start_time=scrapy.Field()
    home=scrapy.Field()
    away=scrapy.Field()
    home_goal=scrapy.Field()
    away_goal=scrapy.Field()
    odds_comp=scrapy.Field()
    one_zero=scrapy.Field()
    two_zero=scrapy.Field()
    two_one=scrapy.Field()
    three_zero=scrapy.Field()
    three_one=scrapy.Field()
    three_two=scrapy.Field()
    four_zero=scrapy.Field()
    four_one=scrapy.Field()
    four_two=scrapy.Field()
    four_three=scrapy.Field()
    zero_one=scrapy.Field()
    zero_two=scrapy.Field()
    one_two=scrapy.Field()
    zero_three=scrapy.Field()
    one_three=scrapy.Field()
    two_three=scrapy.Field()
    zero_four=scrapy.Field()
    one_four=scrapy.Field()
    two_four=scrapy.Field()
    three_four=scrapy.Field()
    zero_zero=scrapy.Field()
    one_one=scrapy.Field()
    two_two=scrapy.Field()
    three_three=scrapy.Field()
    four_four=scrapy.Field()
    returns=scrapy.Field()

class Match500(scrapy.Item):
    id = scrapy.Field()
    home = scrapy.Field()
    away = scrapy.Field()
    home_short = scrapy.Field()
    away_short = scrapy.Field()
    round_txt = scrapy.Field()
    start_time = scrapy.Field()
    home_txt = scrapy.Field()
    away_txt = scrapy.Field()
    home_goal = scrapy.Field()
    away_goal = scrapy.Field()
    home_standing_before = scrapy.Field()
    away_standing_before = scrapy.Field()

class Match500TeamStanding(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    type = scrapy.Field()
    team_type = scrapy.Field()
    match_count = scrapy.Field()
    win = scrapy.Field()
    draw = scrapy.Field()
    lose = scrapy.Field()
    goals = scrapy.Field()
    lost_goals = scrapy.Field()
    total_goals = scrapy.Field()
    marks = scrapy.Field()
    standing = scrapy.Field()
    win_rate = scrapy.Field()

class Match500History(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    league_name = scrapy.Field()
    start_date = scrapy.Field()
    history_url = scrapy.Field()
    home = scrapy.Field()
    away = scrapy.Field()
    home_goal = scrapy.Field()
    away_goal = scrapy.Field()

class Match500Recent(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    league_name = scrapy.Field()
    start_date = scrapy.Field()
    recent_url = scrapy.Field()
    home = scrapy.Field()
    away = scrapy.Field()
    home_goal = scrapy.Field()
    away_goal = scrapy.Field()
    team_type = scrapy.Field()
    recent_type = scrapy.Field()

class Match500Ouzhi(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    comp = scrapy.Field()
    returns = scrapy.Field()
    win = scrapy.Field()
    draw = scrapy.Field()
    lose = scrapy.Field()
    kelly_win = scrapy.Field()
    kelly_draw = scrapy.Field()
    kelly_lose = scrapy.Field()

class Match500Rangqiu(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    comp = scrapy.Field()
    handicap = scrapy.Field()
    returns = scrapy.Field()
    win = scrapy.Field()
    draw = scrapy.Field()
    lose = scrapy.Field()
    kelly_win = scrapy.Field()
    kelly_draw = scrapy.Field()
    kelly_lose = scrapy.Field()

class Match500Daxiao(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    comp = scrapy.Field()
    handicap = scrapy.Field()
    over = scrapy.Field()
    under = scrapy.Field()

class Match500Bifen(scrapy.Item):
    id = scrapy.Field()
    match_id = scrapy.Field()
    comp = scrapy.Field()
    one_zero = scrapy.Field()
    two_zero = scrapy.Field()
    two_one = scrapy.Field()
    three_zero = scrapy.Field()
    three_one = scrapy.Field()
    three_two = scrapy.Field()
    four_zero = scrapy.Field()
    four_one = scrapy.Field()
    four_two = scrapy.Field()
    four_three = scrapy.Field()
    zero_one = scrapy.Field()
    zero_two = scrapy.Field()
    one_two = scrapy.Field()
    zero_three = scrapy.Field()
    one_three = scrapy.Field()
    two_three = scrapy.Field()
    zero_four = scrapy.Field()
    one_four = scrapy.Field()
    two_four = scrapy.Field()
    three_four = scrapy.Field()
    zero_zero = scrapy.Field()
    one_one = scrapy.Field()
    two_two = scrapy.Field()
    three_three = scrapy.Field()
    four_four = scrapy.Field()